apiVersion: apps/v1
kind: Deployment
metadata:
  name: pest-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pest-backend
  template:
    metadata:
      labels:
        app: pest-backend
    spec:
      containers:
        - name: pest-backend
          image: pest-backend:latest     # Use locally built image
          imagePullPolicy: Never         # Don't pull from DockerHub
          ports:
            - containerPort: 5000
          env:
            - name: PYTHONUNBUFFERED     # Optional, for real-time logs
              value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: pest-backend-service
spec:
  type: NodePort  # ✅ This makes it accessible outside the cluster
  selector:
    app: pest-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31500  # optional, pick a port between 30000–32767 or let K8s assign

