apiVersion: apps/v1
kind: Deployment
metadata:
  name: pest-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pest-frontend
  template:
    metadata:
      labels:
        app: pest-frontend
    spec:
      containers:
        - name: pest-frontend
          image: pest-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pest-frontend-service
spec:
  type: NodePort
  selector:
    app: pest-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
